name: optenv
channels:
  - conda-forge
dependencies:
  - pyscipopt=4.3.0
  - pip:
      - bottleneck==1.3.7
      - click==8.1.3
      - cloudpickle==2.2.1
      - dask==2023.3.1
      - deprecation==2.1.0
      - fsspec==2023.3.0
      - highspy==1.5.0.dev0
      - linopy==0.1.3
      - locket==1.0.0
      - numexpr==2.8.4
      - numpy==1.24.2
      - packaging==23.0
      - pandas==1.5.3
      - partd==1.3.0
      - ply==3.11
      - pybind11==2.10.3
      - pyomo==6.5.0
      - python-dateutil==2.8.2
      - pytz==2022.7.1
      - pyyaml==6.0
      - scipy==1.10.1
      - six==1.16.0
      - toolz==0.12.0
      - tqdm==4.65.0
      - xarray==2023.2.0
